### GET request to example server
GET http://localhost:8080

###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "Pranshu",
  "techStack": "Java, Spring Boot"
}

###
GET http://localhost:8080/api/v1/software-engineer


###
GET http://localhost:8080/api/v1/software-engineer/2


###
PUT http://localhost:8080/api/v1/software-engineer/4
Content-Type: application/json


{
  "name": "Pranshu Patel",
  "techStack": "Java, Spring Boot, Docker"
}

###
DELETE http://localhost:8080/api/v1/software-engineer/7

###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "Pranshu",
  "techStack": "Java, Spring Boot"
}


###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "",
  "techStack": "Java"
}


###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "Pranshu"
}


###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "Pranshu",
  "techStack": "Java"
}


###
GET http://localhost:8080/api/v1/software-engineer/999


###
PUT http://localhost:8080/api/v1/software-engineer/999
Content-Type: application/json

{
  "name": "Test",
  "techStack": "Java"
}

###
DELETE http://localhost:8080/api/v1/software-engineer/999


###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "Pranshu",
  "techStack": "Java"
}

###
POST http://localhost:8080/api/v1/software-engineer
Content-Type: application/json

{
  "name": "Pranshu",
  "techStack": "JS"
}

### Explicit pagination
GET http://localhost:8080/api/v1/software-engineer?page=0&size=2

### Next page
GET http://localhost:8080/api/v1/software-engineer?page=1&size=2

###sort by id ascending
GET http://localhost:8080/api/v1/software-engineer?page=0&size=5&sort=id,asc


### sort by id descending
GET http://localhost:8080/api/v1/software-engineer?page=0&size=5&sort=id,desc

###multiple sorts
GET http://localhost:8080/api/v1/software-engineer?page=0&size=5&sort=techStack,asc&sort=id,asc

###filtering,sorting,pagination tests Filtering works independently
#
#Filtering + pagination works together
#
#Sorting still works
#
#Pagination metadata unchanged

GET http://localhost:8080//api/v1/software-engineer

###
GET http://localhost:8080//api/v1/software-engineer?name=an
###
GET http://localhost:8080//api/v1/software-engineer?techStack=java
###
GET http://localhost:8080//api/v1/software-engineer?name=an&techStack=java
###
GET http://localhost:8080//api/v1/software-engineer?page=1&size=3
###
GET http://localhost:8080//api/v1/software-engineer?sort=id,desc


### For Security test requests

### Register User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "pranshu",
  "password": "1234",
  "role": "ROLE_USER"
}



### Login Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "pranshu",
  "password": "1234"
}

###Request With JWT Token with token example ,its valid for  1 hour
GET http://localhost:8080/api/v1/software-engineer
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcmFuc2h1Iiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE3NzEyNjA1NzEsImV4cCI6MTc3MTI2NDE3MX0.lgPiRFyix53XJgjNobYv10P3lf9AbcGPIR21dy3OJQY

### POST with USER token (should return 403)
POST http://localhost:8080/api/v1/software-engineer
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcmFuc2h1Iiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE3NzEyNjA1NzEsImV4cCI6MTc3MTI2NDE3MX0.lgPiRFyix53XJgjNobYv10P3lf9AbcGPIR21dy3OJQY
Content-Type: application/json

{
  "name": "Should Fail",
  "techStack": "Java"
}
