spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://ep-still-flower-aok9i1ki.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_F0IBsJdxMqa5
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=3600000

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.com.learning=DEBUG